---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kubemirror-system

commonLabels:
  app.kubernetes.io/name: kubemirror
  app.kubernetes.io/managed-by: kustomize

resources:
  - namespace.yaml
  - rbac.yaml
  - deployment.yaml
  - service.yaml

images:
  - name: ghcr.io/lukaszraczylo/kubemirror
    newTag: latest
