apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
    - namespaces.yaml
    - https://raw.githubusercontent.com/traefik/traefik/master/docs/content/reference/dynamic-configuration/kubernetes-crd-definition-v1.yml
    - source-secret.yaml
    - source-configmap.yaml
    - traefik-middleware.yaml

commonLabels:
    managed-by: kustomize
    example: kubemirror
