apiVersion: v1
kind: Service
metadata:
  name: {{ include "kubemirror.fullname" . }}-metrics
  labels:
    {{- include "kubemirror.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: metrics
      port: {{ .Values.service.metricsPort }}
      targetPort: metrics
      protocol: TCP
    - name: health
      port: {{ .Values.service.healthPort }}
      targetPort: health
      protocol: TCP
  selector:
    {{- include "kubemirror.selectorLabels" . | nindent 4 }}
